# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsbi', '0004_auto_20170717_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='alejamiento',
            name='dirreccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='fecha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuariobaston',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
